### ISSUE TITLE
HTTPS/HTTP URI

### ISSUE THREAD

**Issue by flightofthunder** [swisscom/gitlab-merge-request-resource#4]
Hi @mastertinner,

I have an issue with the way the HTTP(S) and Gitlab API HTTP(S) requests are made. As it is, `https://` is hardcoded! Example:
```
uri="https://${username}:${password}@${gitlab_host}/${project_path}.git"
```
or
```
open_mrs="$(curl \
--header "PRIVATE-TOKEN: ${private_token}" \
"https://${gitlab_host}/api/v3/projects/${project_path_encoded}/merge_requests?state=opened&order_by=updated_at")"
```
At my organization, we have a local gitlab server, so we don't bother with HTTPS, and use HTTP instead. In order to use your resource, I hardcoded `http://` and pushed my own Docker image in order to use the resource. Eventually, I would like use the `mastertinner/gitlab-merge-request-resource` Docker image, but I cannot do that right now.

My suggestion is to treat the URI similarly to [Concourse's official Git resource](https://github.com/concourse/git-resource) manages it. I think it would be good to get rid of `gitlab_host` and `project_path` and add:

- `uri`: Gitlab URI

Example:

```
http://gitlab.example.com/my/project.git
```
or
```
git@gitlab.example.com:my/project.git
```
- `api_uri`: Gitlab API URI

Example:
```
https://gitlab.example.com/api/v3/projects/my%2Fproject
```
or
```
http://gitlab.example.com/api/v3/projects/my%2Fproject
```

Alternatively, I was thinking we could just add:
- `http_secured`: `true` or `false` (default value `true`)
And we could use HTTPS or HTTP accordingly to this configuration.

This would allow all users to specify the protocol they need to use. I understand the first option would also break the way the resource is currently used, but it is more in line with how the other resources are implemented. Let me know what you think.

**Comment by mastertinner** [comment]
Thanks a lot for the detailed suggestion, @flightofthunder. I think the first option is the way to go (even if it is breaking for our current users). I'll try to implement it soon (or you can PR).

This implementation will require us to parse the git URI to get the project path but I think that should be possible with `sed`.

**Comment by mastertinner** [comment]
@flightofthunder, is this what you had in mind? https://github.com/swisscom/gitlab-merge-request-resource/pull/5

**Comment by flightofthunder** [comment]
Wow, yes that was incredibly quick! It's fantastic, don't even need to have an `api_uri` config because you parse the URI. Great job @mastertinner!

**Comment by mastertinner** [comment]
@flightofthunder, I jus tmerged #5. Please close this issue if it is resolved.

**Comment by flightofthunder** [comment]
Yes, thank you!
